name: GitHub Action Demo
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - name: Log Node & OS Versions
        run: |
          node -v
          cat /etc/os-release
      - name: Log env
        run: /bin/echo --version
  build:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - name: Build
        run: |
          node -v
          cat /etc/os-release
      - name: Build Finished
        run: /bin/echo --version
  deploy:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - name: Deploy
        run: |
          node -v
          cat /etc/os-release
      - name: Deployed
        run: /bin/echo --version