name: GitHub Action Demo
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  Dev:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - name: Log Node & OS Versions
        run: |
          node -v
          cat /etc/os-release
      - name: Log env
        run: /bin/echo --version
  QA:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - name: Log Node & OS Versions
        run: |
          node -v
          cat /etc/os-release
      - name: Log env
        run: /bin/echo --version
  PROD:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - name: Log Node & OS Versions
        run: |
          node -v
          cat /etc/os-release
      - name: Log env
        run: /bin/echo --version